### ISSUE TITLE
Existing project using this technique

### ISSUE THREAD

**Issue by jbjuin** [tanrax/demo-HTML-over-WebSockets-in-Django#1]
Hi @tanrax, just passing by to say that there are already some projects using that technique:

Integrated with Django

- django reactor: https://github.com/edelvalle/reactor this one is awesome: very simple to read & understand the code, think bare django with a touch of vuejs component on top, love it !
- django sockpuppet: https://github.com/jonathan-s/django-sockpuppet/ inspired by a ruby project (stimulus/reflex), never tried, seems more featureful than django-reactor but heavier (with some js)

Without django:

- idom https://idom-docs.herokuapp.com/docs/index.html# here HTML is generated using a python syntax
- https://anvil.works/ this one is proprietary but looks cool nonetheless...
- remi: https://github.com/dddomodossola/remi this is more for "desktop web app" but you can run it remotely as well... there is an integrated GUI (pre-built widgets using Bootstrap)

Anyway your projcet is cool too !

We use django-reactor in production and it is really awesome doing 95% of the work in bare django + python components and adding a grain of js on top. Huge productivity boost for us :). You can just add it in your classical django application to add a pinch of "SPA" on some pages, or go the route of "full reactor". I will publish soon a bunch of helpers to work with reactor: a router (ala vue-router), a store (ala vuex), an integration with graphjs for data viz, an upload helper component, a data table component, etc.

Bye !

Edit: typos

**Comment by tanrax** [comment]
@jbjuin My English is not good enough to answer you as I would like to. I want to thank you for the comment and the information. I will not close the issue so that more people can read it. Thank you!

**Comment by jbjuin** [comment]
Hola Andros,

Integrados en Django

- django reactor: https://github.com/edelvalle/reactor este es muy buno: muy sencillo para leer y entender el codigo. Es quasi "bare" Django con componentes similar a los de vuejs.
- django sockpuppet: https://github.com/jonathan-s/django-sockpuppet/ inspirado de un proyecto Ruby (stimulus/reflex). Nunca lo e probado, parece mas pesado que reactor.

Sin Django:

- idom: https://idom-docs.herokuapp.com/docs/index.html# parecido a componentes React pero en python
- anvil: https://anvil.works/ this one is proprietary but looks cool nonetheless...
- remi: https://github.com/dddomodossola/remi como una application desktop pero con technologica web. Viene con widgets Bootstrap: buttons, sliders, etc.

De toda forma tu proyecto parece muy interessante tambien !

Usamos django-reactor en produccion y es muy util. Podemos hacer 95% del trabajo en Django + python components para el UI con un poco de JS encima. Boost de productividad para nosotros.

Cheers !

**Comment by tanrax** [comment]
Added to README
